trigger:
- main

pool: 
  vmImage: ubuntu-latest

variables:
  tag: "$(Build.BuildId)"
  image: "bashar1993/pygoat"

stages:
 
- stage: build
  jobs:
    - job: build_and_push_app
      displayName: Build and Push App
      steps:

      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.8'
          addToPath: true
          architecture: 'x64'
        displayName: 'Setup Python'

      - script: |
          pip install -r requirements.txt
        displayName: 'Install Dependencies'
      
      - task: Docker@2
        inputs:
          containerRegistry: 'dockerhub'
          repository: '$(image)'
          command: 'buildAndPush'
          Dockerfile: '**/Dockerfile'
        displayName: 'Build and Push Docker image'